version: '3.8'

services:
  ms-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: ms-vue-app
